language: r
cache: packages 
addons:
  apt:
    packages:
      - libssh-dev
      - libjq-dev
      - libharfbuzz-dev
      - libfribidi-dev
r_packages:
  - devtools
  - aws.s3
  - sparklyr
  - resourcer
warnings_are_errors: true
